== Bitcoin

Refers to a protocol, network or a unit of currency.

As a protocol, Bitcoin is a set of rules that every link:../c/Client.asciidoc[client] must follow to accept link:../t/Transction.asciidoc[transactions] and have its own link:../t/Transction.asciidoc[transactions] accepted by other clients. Also includes a message protocol that allows link:../n/Node.asciidoc[nodes] to connect to each other and exchange link:../t/Transction.asciidoc[transactions] and link:../b/Block.asciidoc[blocks].

As a network, Bitcoin is all the computers that follow the same rules and exchange link:../t/Transction.asciidoc[transactions] and link:../b/Block.asciidoc[blocks] between each other.

As a unit, one Bitcoin (link:../b/BTC.asciidoc[BTC], link:../x/XBT.asciidoc[XBT]) is defined as 100 million link:../s/Satoshi.asciidoc[satoshis], the smallest units available in the current link:../t/Transction.asciidoc[transaction] format. 

Bitcoin is written in lower case when speaking about the amount: “I received 0.4 bitcoins.”