== Brain Wallet

Brain wallet is a concept of storing link:../p/Private_Key.ascii[private keys] as a memorable phrase without any digital or paper trace. Either a single key is used for a single link:../a/Address.asciidoc[address], or a link:../d/Deterministic_Wallet.asciidoc[deterministic wallet] derived from a single key.

If done properly, a brain wallet greatly reduces the risk of theft because it is completely deniable: no one could say which or how much bitcoins you own as there are no actual wallet files to be found anywhere. However, it is the most error-prone method as one can simply forget the secret phrase, or make it too simple for anyone to brute force and steal all the funds. Additional risks are added by a complex wallet software. E.g. link:../b/BitcoinQT.asciidoc[BitcoinQT] always sends link:../c/Change.asciidoc[change] amount to a new link:../a/Address.asciidoc[address]. If a link:../p/Private_Key.asciidoc[private key] is imported temporarily to spend 1% of the funds and then the wallet is deleted, the remaining 99% will be lost forever as they are moved as a link:../c/Change.asciidoc[change] to a completely new link:../a/Address.asciidoc[address]. This already happened to a number of people.