== Elliptic Curve Arithmetic

A set of mathematical operations defined on a group of points on a 2D elliptic curve. The link:../b/Bitcoin.asciidoc[Bitcoin protocol] uses predefined curve secp256k1.

Here's the simplest possible explanation of the operations: you can add and subtract points and multiply them by an integer. Dividing by an integer is computationally infeasible (otherwise cryptographic signatures won't work). The link:../p/Private_Key.asciidoc[private key] is a 256-bit integer and the link:../p/Publick_Key.asciidoc[public key] is a product of a predefined point G (“generator”) by that integer: A = G * a.

Associativity law allows implementing interesting cryptographic schemes like Diffie-Hellman key exchange (ECDH): two parties with link:../p/Private_Key.asciidoc[private keys] A and B may exchange their link:../p/Publick_Key.asciidoc[public key] A and B to compute a shared secret point C: C = A * b = B * a because (G * a) * b == (G * b) * a. Then this point C can be used as an AES encryption key to protect their communication channel.