== Fork

Refers either to a fork of a source code (see link:../a/Altcoin.asciidoc[altcoin]) or, more often, to a link:../s/Split.asciidoc[split] of the link:../b/Blockchain.asciidoc[blockchain] when two different parts of the network see different link:../m/Main_Chain.asciidoc[main chains].

In a sense, a fork occurs every time two link:../b/Block.asciidoc[blocks] of the same link:../h/Height.asciidoc[height] are created at the same time. Both link:../b/Block.asciidoc[blocks] always have the different link:../h/Hash.asciidoc[hashes] (and therefore different link:../d/Difficulty.asciidoc[difficulty]), so when a link:../n/Node.asciidoc[node] sees both of them, it will always choose the most difficult one. However, before both link:../b/Block.asciidoc[blocks] arrive to a majority of link:../n/Node.asciidoc[nodes], two parts of the network will see different link:../b/Block.asciidoc[blocks] as tips of the link:../m/Main_main chain.

The term fork (or hard fork) also refers to a change of the protocol that may lead to a split of the network (by design or because of a bug). On March 11 2013 a smaller half of the network running version 0.7 of BitcoinD could not include a large (>900 Kb) link:../b/Block.asciidoc[block] at link:../h/Height.asciidoc[height] 225430 created by a link:../m/Miner.asciidoc[miner] running newer version 0.8. The link:../b/Block.asciidoc[block] could not be included because of the bug in v0.7 which was fixed in v0.8. Since the majority of computing power did not have a problem, it continued to build a chain on top of a problematic link:../b/Block.asciidoc[block]. When the issue was noticed, majority of 0.8 link:../m/Miner.asciidoc[miners] agreed to abandon 24 link:../b/Block.asciidoc[blocks] incompatible with 0.7 link:../m/Miner.asciidoc[miners] and link:../m/Mining.asciidoc[mine] on top of 0.7 chain. Except for one link:../d/Double_Spend.asciidoc[double spend] experiment against OKPay, all link:../t/Transasction.asciidoc[transactions] during the fork were properly included in both sides of the link:../b/Blockchain.asciidoc[blockchain].